targets:
  $default:
    sources:
      - lib/**
      - lib/models/**
    builders:
      chopper_generator:
        options:
          header: "//Generated code"
      swagger_dart_code_generator:
        options:
          input_folder: "lib/models/"
          output_folder: "lib/generated/swagger"